import { valueExchangeSnapshot, type ExchangeStage } from '../../valueExchange';
export function ValueExchange({stage,advance}:{stage:ExchangeStage;advance:()=>void}) {
 const value=valueExchangeSnapshot(stage);
 return <section className="value-exchange">
 <p className="redemption-perspective">02 / REWARD-FUNDED PURCHASE <span>FORM’s fictional policy</span></p><h2>Return the purchase.<br/><em>Reconcile the value.</em></h2>
 <p>This separate example begins with 500 points earned from prior activity. FORM’s conversion is 500 points = one $5 FORM Reward. Earning is 1 point per $1 of qualifying merchandise after reward value is applied.</p>
 <div className="redemption-sequence"><div><small>BEFORE → REDEEM</small><strong>500 → 0 points</strong><span>500 points exchanged for one $5 FORM Reward.</span></div><div><small>PURCHASE</small><strong>+5 points</strong><span>$10 merchandise − $5 reward = $5 qualifying paid spend. $5 normal tender paid; reward consumed.</span></div><div><small>RETURN</small><strong>−5 + 500 points</strong><span>Reverse purchase earning. Restore reward value as points. Refund $5 normal tender.</span></div><div><small>FINAL</small><strong>500 points</strong><span>$5 tender refunded. No active reward. No retained purchase earning or duplicated value.</span></div></div>
 <p className="redemption-conflict">The sequence shows the complete example. Use the actions below to step through its current state. No real payment, coupon, or refund is processed.</p>
 <div className="redemption-outcomes"><section className="redemption-internal"><p className="eyebrow">WHAT FORM SEES / PRODUCT VIEW</p><h2>{['Before redemption','Reward available','Before return','Transaction reconciled'][stage]}</h2><dl><div><dt>Points redeemed</dt><dd>{stage>0?500:0} points</dd></div><div><dt>Reward value created</dt><dd>${value.rewardCreated}</dd></div><div><dt>Reward value used</dt><dd>${value.rewardApplied}</dd></div><div><dt>Qualifying spend for purchase</dt><dd>$5</dd></div><div><dt>Normal tender paid / refunded</dt><dd>${value.tenderPaid} / ${value.tenderRefund}</dd></div><div><dt>Purchase points earned / reversed</dt><dd>{value.earned} / {value.reversed}</dd></div><div><dt>Reward value restored as points</dt><dd>{value.restoredPoints} points</dd></div></dl><p>The return links prior earning, redemption, reward tender, purchase earning, and reversal. Current balance alone cannot explain the transaction. Restore the consumed reward’s value as points; do not also reissue the reward.</p></section>
 <section className="redemption-member-result" aria-live="polite"><p className="eyebrow">WHAT MAYA SEES / MEMBER VIEW</p><h2>{['Your FORM Rewards','Your reward is ready','Purchase complete','Return complete'][stage]}</h2><div className="redemption-number">{value.points}<span>points available</span></div>
 {stage===0 && <p>Redeem 500 points for a $5 FORM Reward. Your points balance will become 0.</p>}
 {stage===1 && <p>One $5 FORM Reward is available. Apply it to $10 merchandise and pay $5 with normal tender. You will earn 5 points on the remaining $5 qualifying spend.</p>}
 {stage===2 && <p>Your $5 reward was used and $5 was paid through your original payment method. You earned 5 points. Returning this item will refund $5, reverse 5 earned points, and restore 500 points from your reward.</p>}
 {stage===3 && <><p>$5 refunded to original payment method.</p><p>500 points restored from FORM Reward.</p><p>5 points earned from the returned purchase reversed.</p></>}
 <p className="redemption-reward-status">{value.rewardAvailable?'$5 FORM Reward · Available':stage===2?'FORM Reward · Used':'No active FORM Reward'}</p>
 {stage<3 && <button className="button primary" onClick={advance}>{['Redeem 500 points','Complete simulated $10 purchase','Return this purchase'][stage]}</button>}
 <section className="redemption-history"><h3>Your points activity</h3><dl>{value.history.map(row=><div key={row.label}><dt>{row.label}</dt><dd>{row.points>0?'+':''}{row.points} points</dd></div>)}<div><dt>Current balance</dt><dd>{value.points} points</dd></div></dl></section></section></div>
 <details className="redemption-reconciliation" open><summary>What should agree?</summary><h3>Original value → linked transactions → matching reversal.</h3><p>At completion: 500 − 500 + 5 − 5 + 500 = 500 points. $5 normal tender paid − $5 refunded = $0 net spent. $5 reward created − $5 consumed = $0 active reward; its value is restored once as 500 points.</p><p>Maya returns to her position before redemption and purchase: 500 points and the $5 she paid, with no merchandise retained. Restored points do not represent new earning.</p></details>
 </section>;
}
