import {ScenarioReset} from "../ScenarioReset";
import {type Dispatch} from 'react';
import {ArrowDown,ArrowRight,Check,Clock3,Monitor,Store} from 'lucide-react';
import {BrandMark} from '../Brand';
import {omniMember,omniSnapshot,type OmniState,type OmniAction} from '../../omnichannelScenario';
import './omnichannel.css';
export function Omnichannel({state,dispatch}:{state:OmniState;dispatch:Dispatch<OmniAction>}) {
 const snapshot=omniSnapshot(state);
 return <div className="omni-page page-shell"><header className="omni-intro"><div><p className="eyebrow">OMNICHANNEL / A FORM PRODUCT STUDY</p><h1>Two channels.<br/><em>One relationship.</em></h1></div><ScenarioReset label="Replay scenario" title="Replay omnichannel scenario?" description="Restore 378 confirmed points: 300 starting + 78 online. The store transaction will be delayed again. Other study scenarios will not be changed." onReset={()=>dispatch({type:'replay'})} /></header>
 <p className="omni-question">How does one rewards experience stay consistent when member activity comes from different channels?</p>
 <p className="omni-context">Separate fictional scenario · Maya starts with 300 confirmed points. Online earning adds 78 before this view opens. Store activity is delayed. This balance is independent of Maya’s main account and every other study scenario. Reset study affects only her main account; replay here resets only this exploration.</p>
 <div className="omni-layout"><section className="omni-product"><p className="eyebrow">PRODUCT VIEW / DIFFERENT ARRIVAL TIMES</p><div className="omni-channels"><article><Monitor size={24}/><p className="eyebrow">ECOMMERCE</p><h2>Online, received.</h2><p>Lift Legging · $78 qualifying spend</p><ol><li>Transaction received</li><li>Member resolved to Maya</li><li>1 point / $1 evaluated</li></ol><strong className="omni-award">+78 <span>points confirmed</span></strong><p className="omni-status"><Check size={14}/>Confirmed · 300 → 378</p></article>
 <article className={snapshot.posConfirmed?'':'omni-delayed'}><Store size={24}/><p className="eyebrow">PHYSICAL STORE / POS</p><h2>{snapshot.posConfirmed?'In store, received.':'In store, delayed.'}</h2><p>Sculpt Bra · $48 store purchase</p><ol>{snapshot.posConfirmed?<><li>POS transaction received</li><li>Member resolved to Maya</li><li>$48 × 1 point / $1</li></>:<><li>Purchase exists in the store scenario</li><li>Transaction not yet received by loyalty</li><li>Earning has not been processed</li></>}</ol><strong className="omni-award">+48 <span>{snapshot.posConfirmed?'points confirmed':'expected once processed'}</span></strong><p className="omni-status">{snapshot.posConfirmed?<Check size={14}/>:<Clock3 size={14}/>} {snapshot.posConfirmed?'Confirmed · 378 → 426':'Pending arrival · not in balance'}</p></article></div>
 <div className="omni-merge"><ArrowDown size={21}/><div><BrandMark/><span>FORM REWARDS</span><strong>{snapshot.balance} confirmed points</strong></div><ArrowDown size={21}/><p>One account → one member-visible balance</p></div>
 <div className="omni-processing"><p>Expected +48 is known from the fictional store scenario, not from loyalty’s confirmed records. Maya’s account has no separate store reference feed, so it cannot display a pending purchase it has not received.</p><button className="button primary" disabled={snapshot.posConfirmed} onClick={()=>dispatch({type:'receive',channel:'pos'})}>{snapshot.posConfirmed?'POS activity processed':'Process delayed POS activity'}<ArrowRight size={16}/></button><div role="status">{snapshot.posConfirmed && <p>Identity matched → $48 qualifying spend → 48 points awarded once → activity confirmed.</p>}</div>
 {snapshot.posConfirmed && <details><summary>What if the store sends it again?</summary><p>The same store transaction reference has already been processed. A retry must not create another points award.</p><button className="text-link" onClick={()=>dispatch({type:'receive',channel:'pos'})}>Send the same POS transaction again</button><p role="status">{state.duplicate?'Already processed. No additional points awarded.':''}</p></details>}</div></section>
 <section className="omni-member" aria-labelledby="omni-member-title"><p className="eyebrow">MEMBER VIEW / WHAT MAYA SEES</p><div className="omni-member-brand">FORM <BrandMark/></div><h2 id="omni-member-title">Your rewards, Maya.</h2><div className="omni-balance" aria-live="polite">{snapshot.balance}<span>points available</span></div><p>One balance. Wherever you move.</p>{!snapshot.posConfirmed && <p className="omni-member-note">Recent in-store activity can take time to appear.</p>}<h3>Your points activity</h3><ul className="omni-history">{[...snapshot.history].reverse().map(row=><li key={row.id}><div><strong>{row.label}</strong><span>{row.spend!==null?`$${row.spend} qualifying spend · `:''}Confirmed</span></div><b>+{row.points}</b></li>)}</ul><p className="omni-history-total">Current balance <strong>{snapshot.balance} points</strong></p></section></div>
 <section className="omni-identity"><p className="eyebrow">PRODUCT DEPENDENCY / ONE MEMBER</p><h2>The same Maya, in both places.</h2><p>Online account → Maya / {omniMember.id}<br/>Store transaction → Maya / {omniMember.id}<br/>Both resolve to one FORM Rewards account.</p><p>The store reference is known to this study; loyalty resolves it when the transaction arrives. This illustrates an identity dependency, not production identity infrastructure.</p></section>
 <section className="omni-reconciliation"><p className="eyebrow">PRODUCT VIEW / WHAT SHOULD AGREE?</p><h2>Different timing. One explainable history.</h2><div className="omni-equation">300 + 78 {snapshot.posConfirmed?'+ 48':''} = <em>{snapshot.balance}</em></div><p>{snapshot.posConfirmed?'Ecommerce and POS activity, loyalty transactions, the confirmed balance, and Maya’s history now agree.':'300 starting points + 78 online points = 378 confirmed. The 48 expected store points are excluded until the transaction arrives. After processing: 300 + 78 + 48 = 426.'}</p><p>The requirement is not that every channel processes at the same moment. Identity must resolve correctly, qualifying activity must be processed once, rules must apply consistently, and duplicate earning must be prevented. The eventual balance and history should tell the same story.</p></section>
 <p className="omni-disclosure">Fictional members and transactions. Local deterministic simulation. No live ecommerce, POS, payment, or identity integration.</p>
</div>;
}
