import { useReducer, type Dispatch } from 'react';
import { ArrowLeft, ArrowRight, Check, RotateCcw } from 'lucide-react';
import { engagementReducer, initialEngagement, objectives, objectiveFor, memberFor, eligibilityFor, programContext, type EngagementState, type EngagementAction } from '../../engagementScenario';
import { experimentFor } from '../../engagementExperiment';
import { CustomerExperience } from './CustomerExperience';
import { ExperimentResult } from './ExperimentResult';
import './engagement.css';
const steps = ['Behavioral objective', 'Audience', 'Eligibility', 'Incentive', 'Success event', 'Experiment', 'Result / Measurement'];
const stepTitles = ['Start with the behavior.', 'A program is not an audience.', 'Relevant does not always mean eligible.', 'Same mechanic. Different job.', 'A purchase is the event that counts.', 'Compare against the normal experience.', 'Measure the difference, not just the response.'];
function ProductStep({ state, dispatch }: { state: EngagementState; dispatch: Dispatch<EngagementAction> }) {
  const objective = objectiveFor(state.objective);
  const experiment = experimentFor(state.objective);
  if (state.step === 0) return <><p className="eng-product-lead">{objective.behavior}</p><div className="eng-insight"><h3>The offer is an implementation choice.</h3><p>Define the change in behavior first. That decision determines who belongs in the audience, what qualifies, and what result would be meaningful.</p></div><div className="eng-definition"><span className="eyebrow">BEHAVIOR TO OBSERVE</span><p>{objective.success}</p></div><p className="eng-product-note">Change the objective above. The 2× points mechanic stays the same; the audience, qualifying event, and measurement strategy change.</p></>;
  if (state.step === 1) return <><p className="eng-product-lead">{objective.audience}</p><div className="eng-audience-path"><div><span>Program context</span><strong>100,000 enrolled</strong></div><ArrowRight size={16} aria-hidden="true" /><div><span>Behavioral criteria</span><strong>{state.objective === 'activate' ? 'Recent enrollment · no purchase' : state.objective === 'second' ? 'One recent qualifying purchase' : 'Previous purchase · 90+ days away'}</strong></div><ArrowRight size={16} aria-hidden="true" /><div><span>Eligibility gates</span><strong>Contactable · promotion eligible</strong></div></div><div className="eng-insight"><h3>Eligible audience size: not supplied.</h3><p>{state.objective === 'activate' ? 'The 42,000 members who have not activated are program context. Not all joined recently, are contactable, or qualify for a promotion. They are not the campaign audience.' : 'Overall enrollment and activation figures do not tell us how many members meet this objective’s criteria. No segment count is assumed.'}</p></div><p className="eng-product-note">Audience membership is evaluated at the experiment start, before observing outcomes.</p></>;
  if (state.step === 2) return <><p className="eng-product-lead">Every rule must pass before assignment. The same eligible population supplies treatment and control.</p><ul className="eng-rule-list">{eligibilityFor(state.objective, memberFor(state.objective)).map(rule => <li key={rule.label}><Check size={16} aria-hidden="true" /><span>{rule.label}</span><small>Pass</small></li>)}</ul><p className="eng-product-note">These checks describe one fictional eligible member, not audience counts. Contactability and promotion eligibility are separate requirements.</p><details className="eng-facts"><summary>Inspect the example member’s facts</summary><p>{state.objective === 'activate' ? 'Joined 10 days before exposure; no qualifying purchases.' : state.objective === 'second' ? 'Joined 180 days before exposure; exactly one qualifying purchase, 10 days before exposure.' : 'Joined 180 days before exposure; one qualifying purchase, 100 days before exposure.'} Contactable and promotion eligible. These are individual demonstration fixtures.</p></details></>;
  if (state.step === 3) return <><p className="eng-product-lead">2× points on the {objective.customerAction}. One qualifying purchase, within {objective.measurementDays} days of exposure.</p><div className="eng-incentive-math"><span>$20 qualifying purchase</span><strong>20 base + 20 extra = 40 points</strong><p>2× is the total award. Normal earning is 20 points.</p></div><div className="eng-insight"><h3>Keep the mechanic. Change the strategy.</h3><p>{objective.behavior} The incentive supports that behavior; it does not define the objective.</p></div><p className="eng-product-note">Study assumptions: 1 base point per $1; one automatic bonus; promotion expiry matches the response window. Tax and shipping are excluded.</p></>;
  if (state.step === 4) return <><p className="eng-product-lead">{objective.success}, within {objective.measurementDays} days of exposure.</p><ol className="eng-event-list"><li><span>Offer viewed</span><strong>No success event</strong></li><li><span>Purchase preview opened</span><strong>No success event</strong></li><li><span>Qualifying purchase completed</span><strong>Success event</strong></li></ol><div className="eng-insight"><h3>{state.purchase ? 'The example member completed the required purchase.' : 'Try the customer experience alongside this view.'}</h3><p>{state.purchase ? `A distinct qualifying purchase was recorded on day ${state.purchase.day}. ${state.objective === 'activate' ? 'This is activation: the first qualifying purchase after enrollment.' : state.objective === 'second' ? 'This is the second purchase, not a duplicate of the first.' : 'This is a return purchase after the 90-day lapse.'}` : 'Opening the preview changes no purchase history and awards no points. Only completing the simulated qualifying purchase meets the success definition.'}</p></div><p className="eng-product-note">Count each member once per outcome window. Duplicate purchase events cannot create additional success or earning.</p></>;
  if (state.step === 5) return <><p className="eng-product-lead">Randomly assign eligible members to two mutually exclusive groups before the offer is shown.</p><div className="eng-arms"><article><span className="eyebrow">TREATMENT · {experiment.treatmentPercent}%</span><h3>2× points</h3><p>The incentive for the selected behavior.</p></article><article><span className="eyebrow">CONTROL · {experiment.controlPercent}%</span><h3>Normal experience</h3><p>Usual earning and benefits. No additional promotional incentive.</p></article></div><p className="eng-product-note">50/50 is a study design assumption. Group sizes and member assignment data are not supplied. These are design proportions, not simulated assignment results.</p><div className="eng-arm-preview"><span className="eyebrow">COMPARE THE CUSTOMER EXPERIENCES</span><div role="group" aria-label="Customer experience to preview">{(['treatment', 'control'] as const).map(arm => <button key={arm} aria-pressed={state.arm === arm} onClick={() => dispatch({ type: 'arm', arm })}>{arm === 'treatment' ? 'Treatment: 2× points' : 'Control: normal program'}</button>)}</div><p>Switching resets only the individual purchase preview. Both groups can complete the qualifying behavior.</p></div><div className="eng-definition"><span className="eyebrow">ONE FAIR OBSERVATION WINDOW</span><p>{objective.measurementDays} days from exposure, with an equivalent index time for control. In this simulation, day 0 is that shared start.</p></div><p className="eng-product-note">Rate = assigned eligible members with the success event ÷ all eligible members assigned to that arm, using a completed observation window. Clicks, opens, and incentive use do not determine who enters the denominator.</p></>;
  return <ExperimentResult objectiveId={state.objective} />;
}
export function EngagementStudy() {
  const [state, dispatch] = useReducer(engagementReducer, initialEngagement);
  const objective = objectiveFor(state.objective);
  return <div className="eng-study page-shell">
    <header className="eng-intro"><div className="eng-masthead"><span className="eyebrow">AN INTERACTIVE PM CASE STUDY</span><a href="#commerce">Commerce & Loyalty <ArrowRight size={12} aria-hidden="true" /></a></div><p className="eng-category">Engagement & Incentives</p><h1>Enrollment <em>≠</em> Activation</h1><p className="eng-deck">How do you design an incentive around the behavior you want to change<br className="eng-desktop-break" /> rather than starting with an offer and measuring who interacted with it?</p></header>
    <aside className="eng-principle"><span className="eyebrow">THE PRODUCT PRINCIPLE</span><h2>The offer is an implementation choice.<br /><em>The product decision starts with the behavior.</em></h2></aside>
    <section className="eng-program" aria-label="Program context, not the eligible campaign audience"><div><span className="eyebrow">PROGRAM CONTEXT ONLY</span><p>Enrollment opens the door.<br />A qualifying purchase marks activation.</p></div><div><strong>{programContext.enrolled.toLocaleString('en-US')}</strong><span>enrolled members</span></div><div><strong>58%</strong><span>58,000 have activated</span></div><div><strong>42,000</strong><span>not activated ≠ eligible audience</span></div></section>
    <section className="eng-objective-picker" aria-labelledby="eng-objective-heading"><div className="eng-section-heading"><h2 id="eng-objective-heading">What behavior should change?</h2><span>ONE MECHANIC / THREE PRODUCT STRATEGIES</span></div><div className="eng-objectives" role="group" aria-label="Behavioral objective">{objectives.map((item, index) => <button key={item.id} aria-pressed={state.objective === item.id} onClick={() => dispatch({ type: 'objective', objective: item.id })}><span>0{index + 1}</span><strong>{item.label}</strong><small>{item.id === 'activate' ? 'From enrollment to first purchase' : item.id === 'second' ? 'From first purchase to a second' : 'From time away to a return'}</small></button>)}</div><p className="eng-assumption">{objective.assumption}</p></section>
    <div className="eng-perspectives"><CustomerExperience state={state} dispatch={dispatch} /><section className="eng-product" aria-labelledby="eng-product-title"><div className="eng-panel-label"><span className="eyebrow">PRODUCT VIEW</span><span>The decisions underneath</span></div><nav aria-label="Product decision sequence"><ol className="eng-steps">{steps.map((step, index) => <li key={step}><button aria-current={state.step === index ? 'step' : undefined} onClick={() => dispatch({ type: 'step', step: index })}><span>{index + 1}</span>{step}</button></li>)}</ol></nav><div className="eng-step-heading"><p className="eyebrow">0{state.step + 1} / {steps[state.step].toUpperCase()}</p><h2 id="eng-product-title">{stepTitles[state.step]}</h2></div><div className="eng-product-content"><ProductStep state={state} dispatch={dispatch} /></div><div className="eng-signal" role="status"><span className={state.purchase ? 'is-complete' : ''} /><p>{state.purchase ? `Example member: qualifying purchase completed on day ${state.purchase.day}.` : state.phase === 'preview' ? 'Example member: preview opened. No new qualifying purchase in this window.' : 'Example member: experience viewed. No new qualifying purchase in this window.'} <strong>Aggregate results stay separate.</strong></p></div><div className="eng-step-controls"><button disabled={state.step === 0} onClick={() => dispatch({ type: 'step', step: state.step - 1 })}><ArrowLeft size={15} aria-hidden="true" />Previous</button><button onClick={() => dispatch({ type: 'replay' })}><RotateCcw size={14} aria-hidden="true" />Replay</button><button disabled={state.step === 6} onClick={() => dispatch({ type: 'step', step: state.step + 1 })}>Next<ArrowRight size={15} aria-hidden="true" /></button></div></section></div>
    <footer className="eng-footer"><p>Fictional members, incentives, and illustrative results. No campaign is sent.<br />A completed qualifying purchase is the event. A comparison with control is the measurement.</p><span>Behavior first.<br />Offer second.</span></footer>
  </div>;
}
